### ISSUE TITLE
refresh dati grib dopo modifica

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/meteomixer#1]
nella finestra di visualizzazione/modifica dati meteo dopo modifiche manuali (e conseguente lancio dello script manual_edit in background) i dati grib dovrebbero essere riletti in modo da rispecchiare il grib modificato (attualmente se modifichi la pioggia di una macroarea e poi passi alla visualizzazione grib le modifiche non si vedono - ma ci sono)

**Comment by spanezz** [comment]
Done in 41ae16d127949823c5a814eb3454b1c87d685951
