### ISSUE TITLE
Visualizzazione dati grigliati read-only

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/meteomixer#11]
Nella mappa coi dati grigliati, visto che non sono modificabili, si possono visualizzare numeri non cliccabili e togliere il cerchietto attorno (il cerchietto non serve e la mappa diventa piú chiara)

**Comment by spanezz** [comment]
Merged for review in branch `rc1.0`

**Comment by brancomat** [comment]
Fixed in branch `rc1.0`
