### ISSUE TITLE
rendere dinamico "project_root" in wsgy.py

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/meteomixer#15]
(disclaimer: domanda potenzialmente poco intelligente)

In fase di deploy se la directory del progetto cambia rispetto a quella salvata nei sorgenti tocca:

1. adattare conf wsgi di apache
2. modificare tutti i path di `settings.py`
3. modificare `project_root`in `wsgy.py`

mentre le prime due modifiche non impattano con il repo git (la 1 è solo accennata nel readme e la 2 è sovrascrivibile facilmente con un `local_settings.py` fuori progetto), nella 3 si edita di fatto un file versionato. Si può aggirare o migliorare in qualche modo?

**Comment by spanezz** [comment]
Penso che l'idea sia che wsgi.py è talmente corto che puoi farne una copia fuori-repo e personalizzarla come vuoi. Per cui direi che la soluzione per la 3 sia fare un wsgi_$sitename.py, fuori progetto, coi path giusti

**Comment by brancomat** [comment]
Ok
