### ISSUE TITLE
aggiornamento a django 2.2 LTS

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/meteomixer#16]
La release candidate per motivi vari sta attraversando un lungo tempo di candidatura e il server candidato è passato da una CentOS 7 con django 1.11 ad una CentOS8 con django 2.2.

@edigiacomo ha tappato un po' di roba e ho pushato il tutto in un branch `rc1.1`, al momento sono fermo qui (il file incriminato è il `settings.py`):

```
$ ./manage.py migrate
SystemCheckError: System check identified some issues:

ERRORS:
?: (admin.E408) 'django.contrib.auth.middleware.AuthenticationMiddleware' must be in MIDDLEWARE in order to use the admin application.
?: (admin.E409) 'django.contrib.messages.middleware.MessageMiddleware' must be in MIDDLEWARE in order to use the admin application.
?: (admin.E410) 'django.contrib.sessions.middleware.SessionMiddleware' must be in MIDDLEWARE in order to use the admin application.
```

**Comment by spanezz** [comment]
Ho fatto push di altre fix.

Ci sono ancora test che non passano, immagino a causa del cambio della lista modelli fatto in 94b2fe39dd680c0458ae339ac855c0061bca9ed7: quando siamo a posto col resto, ditemi qualcosa che cerco di riscrivere quei test, che sarà un lavoro non banale

**Comment by brancomat** [comment]
nella rc1.1 sembrano essere scomparse le informazioni sulla selezione:
![Schermata da 2020-02-06 17-29-00](https://user-images.githubusercontent.com/13255425/73958035-931d6f80-4907-11ea-80d9-4fc984c71828.png)

Prima era così:
![Schermata da 2020-02-06 17-29-12](https://user-images.githubusercontent.com/13255425/73958111-b2b49800-4907-11ea-8037-461d3aaa3be5.png)

la versione in test al momento è raggiungibile internamente come http://meteomixer8.metarpa/

**Comment by spanezz** [comment]
Sistemato. Fammi sapere se ci sono altre cose che non vanno

**Comment by brancomat** [comment]
Grazie, chiudo issue, ne apro di nuove specifiche se emerge altro
