### ISSUE TITLE
Mancanza direzione del vento a +72 ore

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/meteomixer#17]
I comandi:

```
ls -l /autofs/webdata/grib_meteomixer/20200622-00-MMIXER/wdir+*.grib
ls -l /autofs/webdata/grib_meteomixer/20200622-00-MMIXER/ws+*.grib
```
rivelano che meteomixer produce l'intensità del vento fino a 72 ore, ma la direzione ogni 6 (tutte a passi di 6). Dov'è finita la direzione dell'ultima scadenza?

**Comment by brancomat** [comment]
Corretto in 167421e
