### ISSUE TITLE
preservare modifiche dopo cambio modello

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/meteomixer#2]
dopo aver clonato una sessione, possibilità di cambiare i modelli selezionati ma mantenendo le modifiche effettuate a macroaree e punti stazione sul precedente modello (e riapplicare i postprocessing con quei valori, che si traduce in ri-lanciare lo script "manual_edit" per ogni file modificato)
  - a prescindere da clone o no, quando torno indietro e cambio il modello, mantengo le modifiche manuali
  - quindi le modifiche manuali diventano per prodotto e non per modello

**Comment by brancomat** [comment]
todo: definire priorità fra csv macroaree modificati e csv punti stazione

**Comment by spanezz** [comment]
Ho pushato fbb403ec1a340cc7b5cabe77f87516480db0de51 da testare, dovrei aver risolto il problema dei prodotti giornalieri che non venivano visti come modificati, e assieme alle patch di ieri è il momento di testare in produzione se questo problema è stato risolto.

**Comment by brancomat** [comment]
nel frattempo aggiungo che la priorità fra i csv modificati al momento non importa gestirla: si mantengono tutti e si rilancia il postproc su tutti

**Comment by brancomat** [comment]
Modifiche preservate, script manual_edit lanciato a segno (a giudicare dai log, che dalla visualizzazione grib ancora non si vede), per me ok.
