### ISSUE TITLE
colorare diversamente le modifiche

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/meteomixer#3]
mostrare i numeri nella mappa di colore diverso quando sono prodotti modificati
 - e nell'editor, mostrare anche il valore originale
 - e nei bottoni degli step, cambiare il colore dei bottoni se corrispondono a uno step modificato

**Comment by spanezz** [comment]
Done in 8b133d3420b8a1d748c6ec7827e4a29eb4173068
