### ISSUE TITLE
Pulsante per ricaricare dati originali

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/meteomixer#4]
nella visualizzazione con la mappa, possibilità di un pulsante "ricarica dati da modello" che butti via i dati editati manualmente e ricarichi i default del modello (solo per la combinazione visualizzata di csv/modello/scadenza/variabile)

**Comment by spanezz** [comment]
Done in c9e70e23e6326a6850abb3d822d5ccb95c2e21e1
