### ISSUE TITLE
Mascherare pulsanti dopo click

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/meteomixer#5]
Oscurare pulsante subito dopo il click per l'apertura sessione (l'apertura è lenta e il tasto viene cliccato più volte innescando un RuntimeError: A session already exists for this hour e/o un FileExistsError: [Errno 17] File exists: '/autofs/meteomixer/sessions/meteomixer-20150728-0633')

(potenzialmente valido anche per il clone delle sessioni)

**Comment by spanezz** [comment]
Ho aggiunto al template di base un javascript che disabilita al primo click i bottoni che hanno classe 'clickonce'. Sembra funzionare solo per i link che hanno anche la classe 'btn' (gestita da bootstrap).

A sto punto c'è da fare un giro ad aggiungere clickonce a tutti i bottoni a cui serve. Immagino che sul momento ce ne perderemo qualcuno, ma dovrebbe essere poi facile aggiungere la classe ai template alla bisogna.

**Comment by brancomat** [comment]
ok, chiudo, se ne trovo altri modifico di conseguenza
