### ISSUE TITLE
"model" e "validity" in products/list errate

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/meteomixer#6]
Nella finestra con la mappa, la tabella sotto la mappa riporta Variable, Model, Step e Validity: Model e Validity sono errate.

Ad esempio per la corsa ECMWF delle 00 del 2/10, se seleziono la tp +24 ho:
```
Model:    ECMWF 10-02/12
Validity: 10-03/12:00
```

**Comment by spanezz** [comment]
Done in fecf0f232f7ff44eb9193ce8987cb4903ed931d2

**Comment by spanezz** [comment]
(why do people still use 12-based hours, I say)
