### ISSUE TITLE
monitor: passaggio a simclog2

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/meteomixer#8]
Per motivi che narrerò solo davanti ad una birra tra un paio d'anni con il tono da "ma ti ricordi quella volta che...", abbiamo spento `log.metarpa` e quindi l'applicazione `monitor` non funzionava più.

Visto che stamattina serviva meteomixer, ho messo in piedi un "ponte" tra simclog2 e meteomixer che fosse il meno invasivo possibile (quindi: molte aggiunte e poche modifiche al codice esistente):

Il mahckerone è implementato in 947b3f726a3c629be778bb8097879c8578ba7908 e df64521f004f0a3b47f282932f4f8a682c0ec011.

1. I modelli di `monitor` sono adesso locali all'applicazione, in un sqlite a parte.
2. simclog2 invia periodicamente due JSON, uno con l'elenco dei modelli ed uno con l'elenco delle importazioni (vedi `test_data/monitor` per un esempio di file).
3. Il comando `import_json_models` legge i due file e sincronizza i modelli di `monitor`. Ho messo lo script in crontab.

La soluzione ha il grosso difetto di creare un po' di ritardo (al massimo un 20 minuti) tra quando il modello è pronto e quando meteomixer se ne accorge. Pare funzionare e ho messo pure uno straccio di test, però tengo aperto questa issue perché magari ci confrontiamo su come far comunicare in maniera meno complessa i due sistemi.

**Comment by spanezz** [comment]
Ho visto, mi sembra una buona pezza, ci sono per parlare di possibili soluzioni con meno latenza

**Comment by edigiacomo** [comment]
![screenshot from 2019-03-05 17-03-23](https://user-images.githubusercontent.com/927277/53818596-9aeeca00-3f68-11e9-8b87-91c81528b0cd.png)

E.g. http://log.metarpa/simclog2/api/v2/entity/CINECA;cosmo_5M_ita/check_import/201903050000

**Comment by spanezz** [comment]
Per riassumere, serve che meteomixer usi questa API HTTP invece di accedere al DB SQL di simclog2

**Comment by edigiacomo** [comment]
Documentazione corretta:

![image](https://user-images.githubusercontent.com/927277/55096420-2405a680-50ba-11e9-9285-4a2f5a99d5b1.png)

**Comment by spanezz** [comment]
Fatto e mergiato in rc1.0

**Comment by brancomat** [comment]
Ho qualche problemino sul migrate (finisce tutto in un `sqlite3.OperationalError: no such table: imports`)

Log significativi allegati: [migrate_log.txt](https://github.com/ARPA-SIMC/meteomixer/files/3016850/migrate_log.txt)

In generale, ho seguito pedissequamente questi comandi: https://github.com/ARPA-SIMC/meteomixer/blob/rc1.0/README.md#Aggiornamento-da-upstream

**Comment by brancomat** [comment]
Results after the commit: [migrate_log.txt](https://github.com/ARPA-SIMC/meteomixer/files/3018132/migrate_log.txt)

**Comment by spanezz** [comment]
I pushed a new fix: basically, remove all migrations in models/migrations.

Indeed django has never managed that database, since it was an external read only one. The migrations were an artefact of creating fake versions of those tables for testing. Now that I removed the code to manage the readonly tables, those migrations also have to go, as currently they just confuse django

**Comment by brancomat** [comment]
Ok, ci siamo al 99%... resta una roba direi estetica, mi sfugge il ruolo delle tre celle rosse finali:
![Schermata da 2019-03-28 15-16-09](https://user-images.githubusercontent.com/13255425/55164792-9df66800-516c-11e9-8264-62e69e5126fd.png)

per un confronto incollo la vecchia schermata di monitor:
![Schermata da 2019-03-28 15-16-14](https://user-images.githubusercontent.com/13255425/55164871-b8c8dc80-516c-11e9-8d3a-739acce6dfd3.png)

**Comment by spanezz** [comment]
Sistemato!

**Comment by brancomat** [comment]
perfetto, considero il tutto fixed in `rc1.0`
